name: Build CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  Build-kpimg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Generate version
        id: parse_version
        run: |
          MAJOR=$(grep '#define MAJOR' version.h | awk '{print $3}')
          MINOR=$(grep '#define MINOR' version.h | awk '{print $3}')
          PATCH=$(grep '#define PATCH' version.h | awk '{print $3}')
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Generated Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Install Toolchains
        env:
          packages:
            binutils-aarch64-linux-gnu
            binutils-arm-linux-gnueabi
            binutils-i686-linux-gnu
            binutils-x86-64-linux-gnu
            g++-aarch64-linux-gnu
            g++-arm-linux-gnueabi
            g++-i686-linux-gnu
            g++-x86-64-linux-gnu
            zlib1g-dev
            make
        run: |
          sudo apt install ${{ env.packages }} -y

      - name: Build
        run: |
          make TARGET_COMPILE=aarch64-linux-gnu-
          mv patcher sukisu-kpm-patcher-aarch64
          make TARGET_COMPILE=arm-linux-gnueabi-
          mv patcher sukisu-kpm-patcher-arm
          make TARGET_COMPILE=x86-64-linux-gnu-
          mv patcher sukisu-kpm-patcher-x86_64
          make TARGET_COMPILE=i686-linux-gnu
          mv patcher sukisu-kpm-patcher-x86

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag: ${{ steps.parse_version.outputs.VERSION }}
          files: |
            sukisu-kpm-patcher-x86
            sukisu-kpm-patcher-x86_64
            sukisu-kpm-patcher-aarch64
            sukisu-kpm-patcher-arm
