name: Build CI

on:
  workflow_call:
  workflow_dispatch:

jobs:
  Build-kpimg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Generate version
        id: parse_version
        run: |
          MAJOR=$(grep '#define MAJOR' version.h | awk '{print $3}')
          MINOR=$(grep '#define MINOR' version.h | awk '{print $3}')
          PATCH=$(grep '#define PATCH' version.h | awk '{print $3}')
          VERSION="$MAJOR.$MINOR.$PATCH"
          echo "Generated Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Toolchains
        env:
          packages:
            binutils-aarch64-linux-gnu
            binutils-x86-64-linux-gnu
            gcc-aarch64-linux-gnu
            gcc-x86-64-linux-gnu
            g++-aarch64-linux-gnu
            g++-x86-64-linux-gnu
            make
        run: |
          sudo apt install ${{ env.packages }} -y
          git clone https://github.com/awkoo/aarch64-none-elf.git -q -b x86_64
          echo "PATH=$GITHUB_WORKSPACE/aarch64-none-elf/bin/:$PATH" >> $GITHUB_ENV

      - name: Build
        run: |
          make TARGET_COMPILE=aarch64-linux-gnu-
          mv sukisu-kpm-patcher sukisu-kpm-patcher-aarch64
          make TARGET_COMPILE=x86_64-linux-gnu-
          mv sukisu-kpm-patcher sukisu-kpm-patcher-x86_64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.parse_version.outputs.VERSION }}
          files: |
            sukisu-kpm-patcher-aarch64
            sukisu-kpm-patcher-x86_64
